[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src 'none'; script-src 'self'; connect-src 'self' https://*.openai.com https://startupsolechatboot.netlify.app; img-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';"
