[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://startupsolechatboot.netlify.app/.netlify/functions/openaiFirebaseProxy https://*.openai.com; script-src 'self'; style-src 'self'; frame-src 'self';"