[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline'; frame-src *;"
