[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["firebase", "openai", "node-fetch", "rss-parser"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://startupsolechatboot.netlify.app https://*.openai.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-src 'self';"
