[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["firebase", "openai", "node-fetch", "rss-parser"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
